FROM nginx:alpine

RUN apk add --no-cache openssl

COPY ./app/ChatApplication-main/react-client/build /usr/share/nginx/html

COPY docker/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
